### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by strataga** [pocesar/react-native-stager#6]
![screen shot 2017-12-27 at 12 39 34 pm](https://user-images.githubusercontent.com/10903600/34390223-f232a738-eb03-11e7-8122-37256f5bc140.png)

v0.2.3 works fine.

```
"dependencies": {
    "@expo/vector-icons": "6.2.2",
    "axios": "0.17.1",
    "bson-objectid": "1.2.2",
    "clone": "2.1.1",
    "expo": "24.0.2",
    "lodash": "4.17.4",
    "moment": "2.20.1",
    "native-base": "2.3.5",
    "prop-types": "15.6.0",
    "react": "16.2.0",
    "react-native": "0.51.0",
    "react-native-atoz-list": "1.0.2",
    "react-native-datepicker": "1.6.0",
    "react-native-easy-grid": "0.1.15",
    "react-native-fit-image": "1.5.4",
    "react-native-image-progress": "1.0.1",
    "react-native-modal": "4.1.1",
    "react-native-pin-input": "1.2.9",
    "react-native-stager": "0.2.4",
    "react-native-star-rating": "1.0.8",
    "react-native-svg-image": "2.0.1",
    "react-native-vector-icons": "4.4.3",
    "react-navigation": "1.0.0-beta.21",
    "react-redux": "5.0.6",
    "redux": "3.7.2",
    "redux-logger": "3.0.6",
    "redux-thunk": "2.2.0",
    "sentry-expo": "1.7.0",
    "slack-notify": "0.1.6",
    "validator": "9.2.0"
  }
```

**Comment by strataga** [comment]
![screen shot 2017-12-27 at 12 57 59 pm](https://user-images.githubusercontent.com/10903600/34390486-a3fda912-eb05-11e7-8212-3573c0c573ae.png)

**Comment by pocesar** [comment]
have you linked it? `react-native link react-native-stager`

**Comment by strataga** [comment]
You don’t do that with create-react-native-app. It’s automatic.

~ Jason

**Comment by pocesar** [comment]
hmm weird, seems that the `lib` folder is missing from the release, i'll bump it to 0.2.5

**Comment by pocesar** [comment]
should be good to go (for 1.0.0), had to fix some outdated deps for the publish to work

**Comment by wesguirra** [comment]
Dead repo?

**Comment by pocesar** [comment]
nope, still using it in production, but could be refactored to use the new Context API in 16.3, just not sure how well it's supported in current React Native version

was actually waiting for the OP feedback that it worked to close the issue :)
