### ISSUE TITLE
Override stager/stage styles

### ISSUE THREAD

**Issue by alterx** [pocesar/react-native-stager#7]
Hey, first of all I wanted to thank you for your hard work in this component, it's been super useful and the most adequate solution for my use case.

Cutting to the chase, I want the stage to use 100% of the available height so, no matter what, the stage buttons are always at the bottom of the screen. Is that possible?

**Comment by pocesar** [comment]
by default, it'll always stick to the edges of the available area but will try to compensate for the prev/next button area https://github.com/pocesar/react-native-stager/blob/master/src/index.tsx#L55-L62

although not ideal (and usually not endorsed when doing React, by using inheritance), you could extend the Stager / Stage override and implement your own stuff like:

```tsx
class MyStage extends Stage { 
  render() {
    /* your stuff with your styles */
  }
}

class MyStager extends Stager { 
  render() {
    /* your stuff with your styles */
  }
}
```

would just need to make sure to place the correct `props` and `state` members on their places, and you should be good to go.

I could of course make some changes and add a `render` or `component` prop, but passing the needed information as `render props` to yet another prop might go overboard. also with the new context API, it would need to be changed nevertheless

also, now that I'm thinking about it, I'm not sure if you modify the `import { styles } from 'react-native-stager'` would be possible, if so, you could just edit the hardcoded style to your liking

**Comment by alterx** [comment]
Yeah @pocesar , inheriting is the last thing I want to do. That's why I reached to you, maybe there was something else that could be done.

What you say is interesting, tho. I'm seeing something slightly different with the stage and the buttons: they get pushed up if the contents of the stage are not filling the full height of the container.

![buttons](https://user-images.githubusercontent.com/1593752/38263290-fa00e4c8-372c-11e8-8c06-18ef02711b54.gif)

**Comment by pocesar** [comment]
have you tried using `StageButtons` with a position absolute? have you set your parent `View` (of the Stager) to use all the window height as well?

**Comment by alterx** [comment]
Yeah, I'm using NativeBase and it turns out I needed to add a couple of extra styles on my end :) 
Thanks for the quick response.
